name: 'esquio-set-parameter-v3'
description: 'Xabaril Esquio set parameter task (V3)'
author: 'Xabaril'
branding:
  icon: 'toggle-right'  
  color: 'blue'
inputs:
  esquio-url:             
    required: true
    description: 'Esquio URL'
  esquio-api-key:
    required: true
    description: 'Esquio API KEy (keep it secret)'
  product-name:
    required: true
    description: 'Product name'
  feature-name:
    required: true
    description: 'Feature name'
  toggle-type:
    required: true
    description: 'Toggle type in the feature'
  parameter-name:
    required: true
    description: 'Parameter name to set the value'
  value:
    required: true
    description: 'Value for the parameter'
  deployment-name:
    required: false
    description: 'Name of the deplyment you want to set the value for (if you are using rings, otherwise leave empty)'
runs:
  using: 'node12'
  main: 'lib/main.js'
